#%RAML 1.0
title: Order API 
version: v1.0
baseUri: http://alexfernandezorder/api
mediaType: application/json
documentation:
  - title: Welcome to the order process management api
    content: |
      API to create and retrieve Orders
/orders:
  get:
    responses:
      200:
         description: |
            Retrieves all the orders
            body:
              application/json:
                example: !include examples/v1/GetOrderResponseSuccess.json
      400:
            description: |
              Bad Request.
            body:
              application/json:
                example: !include examples/v1/GetOrderResponseBadRequest.json
      500:
            description: |
              Server error.
            body:
              application/json:
                example: !include examples/v1/GetOrderResponseBadRequest.json
  /{orderId}:
    get:
      responses:
        200:
          body:
            application/json:
             example: !include examples/v1/GetOrderResponseSuccess.json
        400:
            description: |
              Bad Request.
            body:
              application/json:
                example: !include examples/v1/GetOrderResponseBadRequest.json
        500:
            description: |
              Server error.
            body:
              application/json:
                example: !include examples/v1/GetOrderResponseBadRequest.json